---
Name: remoteassetdownload
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
    rules:
        'remoteassetreadfiles/$daysago/$offset' : 'OP\RemoteAssetReadFilesController'
        'remoteassetdownloadfiles' : 'OP\RemoteAssetDownloadFilesController'

