---
Name: remoteassetsync
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
    rules:
        'remoteassetlist/$AccessKey!' : 'OP\RemoteAssetListController'
        'remoteassetdiff/$AccessKey!' : 'OP\RemoteAssetDiffController'
        'remoteassetdownload/$AccessKey!' : 'OP\RemoteASsetDownloadController'
