---
Name: remoteassetdownload
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
    rules:
        'RemoteAssetReadFilesController/$offset' : 'OP\RemoteAssetReadFilesController'
        'RemoteAssetDownloadFilesController' : 'OP\RemoteAssetDownloadFilesController'

